steps:
    - label: Running Test
      command: 'scripts/test.sh'
      
    # - label: Running lint
    #   command: 'scripts/test_lint.sh'

    - label: Deploy Project
      command: 'scripts/serverless_script.sh'